version: '3.2'
services:
  bblfsh:
    image: bblfsh/bblfshd:v2.13.0-drivers
    privileged: true
    ports:
      - 9432:9432
    restart: always

  gitbase:
    image: srcd/gitbase:v0.20.0-beta4
    ports:
      - 3306:3306
    environment:
      BBLFSH_ENDPOINT: bblfsh:9432
    depends_on:
      - bblfsh
    volumes:
      - type: bind
        source: ${GITBASE_REPOS_DIR}
        target: /opt/repos
        read_only: true
        consistency: delegated
      - gitbase_indexes:/var/lib/gitbase/index
    restart: always

  bblfsh-web:
    image: bblfsh/web:v0.11.0
    command: -bblfsh-addr bblfsh:9432
    ports:
      - 9999:8080
    depends_on:
      - bblfsh

  redis:
    image: redis:3.2
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  postgres:
    image: postgres:10
    restart: unless-stopped
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  superset:
    image: srcd/superset:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      GITBASE_DB: gitbase
      GITBASE_USER: root
      GITBASE_PASSWORD:
      GITBASE_HOST: gitbase
      GITBASE_PORT: 3306
      BBLFSH_WEB_HOST: bblfsh-web
      BBLFSH_WEB_PORT: 8080
      SUPERSET_ENV: production
    ports:
      - 8088:8088
    depends_on:
      - postgres
      - redis
      - gitbase

volumes:
  gitbase_indexes:
    external: false
  postgres:
    external: false
  redis:
    external: false
